# Travis CI (https://travis-ci.org/)
# This will only work on your repo if you have an account on travis and you
# have set it up to run continuous integration on this this repo

# Linux distribution
dist: bionic

# Language and version
language: python
python:
  - "3.6" # current default Python on Travis CI

cache:
  apt: true # only works with Pro version

env:
  global: # define environment variables for bash
    - OCTFLAGS="--no-gui --no-window-system --silent"

before_install:
  - travis_retry sudo apt-get -y -qq update
  # install octave
  - travis_retry sudo apt-get -y install octave
  - travis_retry sudo apt-get -y install liboctave-dev
  # install miss_hit linter
  - pip3 install miss_hit

before_script:
  # Add to src functions to path
  - octave $OCTFLAGS --eval "addpath(genpath(fullfile(pwd, 'src'))); savepath ();"

jobs:
  include:
    - name: "miss_hit: checking code quality"
      script: mh_metric . --ci
    - name: "miss_hit: checking code style"
      script: mh_style .
      
    